### ISSUE TITLE
Release on wordpress.org

### ISSUE THREAD

**Issue by openmindculture** [openmindculture/wp-contact-form-inbox-report-mailer-plugin#7]
It might be helpful to release Contact Form Inbox Report Mailer as an official plugin once its mature enough, i.e. stable, tested and with basic configuration options #5 . Tested might mean adding unit tests #4 but it might also mean proved by running in more than 1 real-world production systems and passing  static code analysis and the plugin marketplace submission criteria.

As the classic WP code style predates PSR, that means we either follow WP code style or modern PHP code style. I would prefer the latter one, which also makes it much easier to use default coding assistance in PhpStorm. But beside the spaces and braces conventions, some of the submission criteria benefit security as well. Releasing also means more testing, feedback and possible contribution, which can also benefit the project. Hopefully, the old code style is not mandatory anymore?

Why I did not submit the plugin yet:

- [ ] essential functionality not working yet #3 
- [ ] missing configuration options #5 
- [ ] unsure about submission criteria #2 
- [ ] review queue > 1000 unreviewed submitted new plugins on wordpress.org = expected time to wait for review 99 days+

In that 99+ days, I will probably add several improvements to the code and the queue will hopefully get smaller.
